# Generated by Django 4.0.2 on 2022-03-05 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_options_remove_instructor_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile',
        ),
    ]
