# Generated by Django 4.0.2 on 2022-03-05 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.profile'),
        ),
    ]
