# Generated by Django 4.0.3 on 2022-03-11 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_student_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='applied_project',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_leader',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='projectId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_leader',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='projectId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectId', models.CharField(max_length=200, null=True)),
                ('projectName', models.CharField(max_length=200, null=True)),
                ('teamName', models.CharField(max_length=200, null=True)),
                ('project_idea', models.CharField(max_length=800, null=True)),
                ('projectIntroduction', models.CharField(max_length=800, null=True)),
                ('teamMemName', models.EmailField(max_length=254, null=True, unique=True)),
                ('intendedLanguage', models.CharField(max_length=200, null=True)),
                ('otherLanguage', models.CharField(max_length=200, null=True)),
                ('skillWanted', models.CharField(max_length=200, null=True)),
                ('keywords', models.CharField(max_length=300, null=True)),
                ('type', models.PositiveSmallIntegerField(default=1, null=True)),
                ('applied_stu', models.EmailField(max_length=254, null=True, unique=True)),
                ('teamLeader', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.student')),
            ],
        ),
    ]
