# Generated by Django 4.1 on 2022-03-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_student_applied_project_student_is_leader_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_idea",
        ),
        migrations.RemoveField(
            model_name="project",
            name="type",
        ),
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="applied_stu",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="teamMemName",
            field=models.JSONField(null=True, unique=True),
        ),
    ]
