# Generated by Django 4.1 on 2022-03-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_remove_project_project_idea_remove_project_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="applied_stu",
            field=models.JSONField(null=True, unique=True),
        ),
    ]
