# Generated by Django 4.0.2 on 2022-03-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_student_applied_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='applied_stu',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='intendedLanguage',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='keywords',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='otherLanguage',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='skillWanted',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='teamMemName',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='projectId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
