# Generated by Django 4.0.2 on 2022-03-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_project_applied_stu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='keywords',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='skillWanted',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
