# Generated by Django 4.1 on 2022-03-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_project_keywords_alter_project_skillwanted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="checkedLanguage",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="otherLanguage",
            new_name="mbti",
        ),
        migrations.AddField(
            model_name="profile",
            name="userProject",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="fieldInt",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skillLevel",
            field=models.JSONField(default=list, null=True),
        ),
    ]
