# Generated by Django 4.1 on 2022-03-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_rename_checkedlanguage_profile_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="contactsList",
            field=models.JSONField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="messageList",
            field=models.JSONField(null=True, unique=True),
        ),
    ]
