# Generated by Django 4.0.2 on 2022-04-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_student_contactslist_student_messagelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prod',
            field=models.JSONField(default=list, null=True),
        ),
    ]
