# Generated by Django 4.0.2 on 2022-04-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_profile_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prod',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
