# Generated by Django 4.0.2 on 2022-04-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactTag', models.CharField(max_length=200, null=True)),
                ('instructorName', models.CharField(max_length=200, null=True)),
                ('instructorEmail', models.CharField(max_length=200, null=True)),
                ('zoomLink', models.CharField(max_length=200, null=True)),
                ('Ta', models.JSONField(default=list, null=True)),
                ('officeHour', models.JSONField(default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='prj_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupTag', models.CharField(max_length=200, null=True)),
                ('groupinfo', models.JSONField(default=list, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='group_selection',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
