# Generated by Django 4.0.2 on 2022-04-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_instructor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='contactsList',
            field=models.JSONField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='messageList',
            field=models.JSONField(null=True, unique=True),
        ),
    ]
